[2025-04-29T06:10:20.965+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hourly_forecast_dag.run_future_load_forecast scheduled__2025-04-29T02:00:00+00:00 [queued]>
[2025-04-29T06:10:20.983+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hourly_forecast_dag.run_future_load_forecast scheduled__2025-04-29T02:00:00+00:00 [queued]>
[2025-04-29T06:10:20.984+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-29T06:10:21.018+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_future_load_forecast> on 2025-04-29 02:00:00+00:00
[2025-04-29T06:10:21.032+0000] {standard_task_runner.py:60} INFO - Started process 89 to run task
[2025-04-29T06:10:21.038+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hourly_forecast_dag', 'run_future_load_forecast', 'scheduled__2025-04-29T02:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/forecast_dag.py', '--cfg-path', '/tmp/tmpt928jm1w']
[2025-04-29T06:10:21.041+0000] {standard_task_runner.py:88} INFO - Job 89: Subtask run_future_load_forecast
[2025-04-29T06:10:21.162+0000] {task_command.py:423} INFO - Running <TaskInstance: hourly_forecast_dag.run_future_load_forecast scheduled__2025-04-29T02:00:00+00:00 [running]> on host 58c0d1847783
[2025-04-29T06:10:21.318+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hourly_forecast_dag' AIRFLOW_CTX_TASK_ID='run_future_load_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-04-29T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-29T02:00:00+00:00'
[2025-04-29T06:10:22.349+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [06:10:22] WARNING: /workspace/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)

[2025-04-29T06:10:22.549+0000] {logging_mixin.py:188} INFO - âœ… Data upserted successfully!
[2025-04-29T06:10:22.561+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-29T06:10:22.576+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=hourly_forecast_dag, task_id=run_future_load_forecast, execution_date=20250429T020000, start_date=20250429T061020, end_date=20250429T061022
[2025-04-29T06:10:22.635+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-29T06:10:22.668+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
