[2025-04-28T18:53:03.756+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T18:53:01.082842+00:00 [queued]>
[2025-04-28T18:53:03.765+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T18:53:01.082842+00:00 [queued]>
[2025-04-28T18:53:03.766+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-28T18:53:03.780+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_load_forecast> on 2025-04-28 18:53:01.082842+00:00
[2025-04-28T18:53:03.790+0000] {standard_task_runner.py:60} INFO - Started process 5321 to run task
[2025-04-28T18:53:03.793+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_forecast_dag', 'run_load_forecast', 'manual__2025-04-28T18:53:01.082842+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/historical_predictions_dag.py.py', '--cfg-path', '/tmp/tmp3gk1utfi']
[2025-04-28T18:53:03.794+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask run_load_forecast
[2025-04-28T18:53:03.848+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T18:53:01.082842+00:00 [running]> on host 5464d109121d
[2025-04-28T18:53:03.937+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_forecast_dag' AIRFLOW_CTX_TASK_ID='run_load_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T18:53:01.082842+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T18:53:01.082842+00:00'
[2025-04-28T18:53:05.038+0000] {logging_mixin.py:188} INFO - Index(['timestamp', 'stn', 'dd', 'fh', 'ff', 'fx', 't', 't10n', 'td', 'sq',
       'q', 'dr', 'rh', 'p', 'vv', 'n', 'u', 'ww', 'ix', 'm', 'r', 's', 'o',
       'y', 'T', 'hour', 'day_of_week', 'month', 'is_weekend', 'is_holiday'],
      dtype='object')
[2025-04-28T18:53:05.115+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [18:53:05] WARNING: /workspace/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)

[2025-04-28T18:53:05.484+0000] {logging_mixin.py:188} INFO - ‚ùå Error: column "index" of relation "historical_load_predictions" does not exist
LINE 2: ...SERT INTO "public"."historical_load_predictions" (index, tim...
                                                             ^
[2025-04-28T18:53:05.492+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-28T18:53:05.505+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_forecast_dag, task_id=run_load_forecast, execution_date=20250428T185301, start_date=20250428T185303, end_date=20250428T185305
[2025-04-28T18:53:05.572+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T18:53:05.594+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
