[2025-04-28T19:12:49.029+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:12:46.380270+00:00 [queued]>
[2025-04-28T19:12:49.042+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:12:46.380270+00:00 [queued]>
[2025-04-28T19:12:49.042+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-28T19:12:49.059+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_load_forecast> on 2025-04-28 19:12:46.380270+00:00
[2025-04-28T19:12:49.070+0000] {standard_task_runner.py:60} INFO - Started process 5954 to run task
[2025-04-28T19:12:49.074+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_forecast_dag', 'run_load_forecast', 'manual__2025-04-28T19:12:46.380270+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/historical_predictions_dag.py.py', '--cfg-path', '/tmp/tmpep0c86nh']
[2025-04-28T19:12:49.076+0000] {standard_task_runner.py:88} INFO - Job 69: Subtask run_load_forecast
[2025-04-28T19:12:49.144+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:12:46.380270+00:00 [running]> on host 5464d109121d
[2025-04-28T19:12:49.241+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_forecast_dag' AIRFLOW_CTX_TASK_ID='run_load_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T19:12:46.380270+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T19:12:46.380270+00:00'
[2025-04-28T19:12:51.148+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [19:12:51] WARNING: /workspace/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)

[2025-04-28T19:12:51.163+0000] {logging_mixin.py:188} INFO - Index(['hour', 'day_of_week', 'month', 'is_weekend', 'is_holiday', 'T',
       'heating_degree', 'cooling_degree'],
      dtype='object')
[2025-04-28T19:12:51.163+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/historical_predictions_dag.py.py", line 31, in forecast_task
    run_forecast_pipeline(
  File "/opt/airflow/dags/tasks/historical_predictions.py", line 151, in run_forecast_pipeline
    predictions = predict_load(feature_df, model)
  File "/opt/airflow/dags/tasks/historical_predictions.py", line 88, in predict_load
    raise ValueError("Feature dataframe must contain a 'timestamp' column.")
ValueError: Feature dataframe must contain a 'timestamp' column.
[2025-04-28T19:12:51.179+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=daily_forecast_dag, task_id=run_load_forecast, execution_date=20250428T191246, start_date=20250428T191249, end_date=20250428T191251
[2025-04-28T19:12:51.198+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 69 for task run_load_forecast (Feature dataframe must contain a 'timestamp' column.; 5954)
[2025-04-28T19:12:51.231+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-28T19:12:51.259+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
