[2025-04-28T19:22:52.079+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:22:50.106031+00:00 [queued]>
[2025-04-28T19:22:52.096+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:22:50.106031+00:00 [queued]>
[2025-04-28T19:22:52.097+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-28T19:22:52.121+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_load_forecast> on 2025-04-28 19:22:50.106031+00:00
[2025-04-28T19:22:52.134+0000] {standard_task_runner.py:60} INFO - Started process 6291 to run task
[2025-04-28T19:22:52.139+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_forecast_dag', 'run_load_forecast', 'manual__2025-04-28T19:22:50.106031+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/historical_predictions_dag.py.py', '--cfg-path', '/tmp/tmpbv5e_5b8']
[2025-04-28T19:22:52.141+0000] {standard_task_runner.py:88} INFO - Job 73: Subtask run_load_forecast
[2025-04-28T19:22:52.211+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:22:50.106031+00:00 [running]> on host 5464d109121d
[2025-04-28T19:22:52.299+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_forecast_dag' AIRFLOW_CTX_TASK_ID='run_load_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T19:22:50.106031+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T19:22:50.106031+00:00'
[2025-04-28T19:22:53.368+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [19:22:53] WARNING: /workspace/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)

[2025-04-28T19:22:53.381+0000] {logging_mixin.py:188} INFO - Index(['hour', 'day_of_week', 'month', 'is_weekend', 'is_holiday', 'T',
       'heating_degree', 'cooling_degree', 'timestamp'],
      dtype='object')
[2025-04-28T19:22:54.147+0000] {logging_mixin.py:188} INFO - âœ… Data upserted successfully!
[2025-04-28T19:22:54.158+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-28T19:22:54.172+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_forecast_dag, task_id=run_load_forecast, execution_date=20250428T192250, start_date=20250428T192252, end_date=20250428T192254
[2025-04-28T19:22:54.289+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T19:22:54.313+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
