[2025-04-28T19:10:44.103+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:10:41.942418+00:00 [queued]>
[2025-04-28T19:10:44.112+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:10:41.942418+00:00 [queued]>
[2025-04-28T19:10:44.113+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-28T19:10:44.127+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_load_forecast> on 2025-04-28 19:10:41.942418+00:00
[2025-04-28T19:10:44.138+0000] {standard_task_runner.py:60} INFO - Started process 5858 to run task
[2025-04-28T19:10:44.143+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_forecast_dag', 'run_load_forecast', 'manual__2025-04-28T19:10:41.942418+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/historical_predictions_dag.py.py', '--cfg-path', '/tmp/tmpzzoct8yv']
[2025-04-28T19:10:44.144+0000] {standard_task_runner.py:88} INFO - Job 66: Subtask run_load_forecast
[2025-04-28T19:10:44.195+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:10:41.942418+00:00 [running]> on host 5464d109121d
[2025-04-28T19:10:44.301+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_forecast_dag' AIRFLOW_CTX_TASK_ID='run_load_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T19:10:41.942418+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T19:10:41.942418+00:00'
[2025-04-28T19:10:45.623+0000] {logging_mixin.py:188} INFO - Index(['timestamp', 'stn', 'dd', 'fh', 'ff', 'fx', 't', 't10n', 'td', 'sq',
       'q', 'dr', 'rh', 'p', 'vv', 'n', 'u', 'ww', 'ix', 'm', 'r', 's', 'o',
       'y', 'T', 'hour', 'day_of_week', 'month', 'is_weekend', 'is_holiday'],
      dtype='object')
[2025-04-28T19:10:45.716+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [19:10:45] WARNING: /workspace/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)

[2025-04-28T19:10:45.733+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/historical_predictions_dag.py.py", line 31, in forecast_task
    run_forecast_pipeline(
  File "/opt/airflow/dags/tasks/historical_predictions.py", line 152, in run_forecast_pipeline
    predictions = predict_load(feature_df, model)
  File "/opt/airflow/dags/tasks/historical_predictions.py", line 89, in predict_load
    raise ValueError("Feature dataframe must contain a 'timestamp' column.")
ValueError: Feature dataframe must contain a 'timestamp' column.
[2025-04-28T19:10:45.746+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=daily_forecast_dag, task_id=run_load_forecast, execution_date=20250428T191041, start_date=20250428T191044, end_date=20250428T191045
[2025-04-28T19:10:45.763+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 66 for task run_load_forecast (Feature dataframe must contain a 'timestamp' column.; 5858)
[2025-04-28T19:10:45.799+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-28T19:10:45.822+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
