[2025-04-28T19:17:14.349+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:17:12.219720+00:00 [queued]>
[2025-04-28T19:17:14.360+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:17:12.219720+00:00 [queued]>
[2025-04-28T19:17:14.361+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-28T19:17:14.380+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_load_forecast> on 2025-04-28 19:17:12.219720+00:00
[2025-04-28T19:17:14.391+0000] {standard_task_runner.py:60} INFO - Started process 6090 to run task
[2025-04-28T19:17:14.395+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_forecast_dag', 'run_load_forecast', 'manual__2025-04-28T19:17:12.219720+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/historical_predictions_dag.py.py', '--cfg-path', '/tmp/tmpkr9deefg']
[2025-04-28T19:17:14.397+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask run_load_forecast
[2025-04-28T19:17:14.464+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_forecast_dag.run_load_forecast manual__2025-04-28T19:17:12.219720+00:00 [running]> on host 5464d109121d
[2025-04-28T19:17:14.578+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_forecast_dag' AIRFLOW_CTX_TASK_ID='run_load_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T19:17:12.219720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T19:17:12.219720+00:00'
[2025-04-28T19:17:15.950+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [19:17:15] WARNING: /workspace/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)

[2025-04-28T19:17:15.964+0000] {logging_mixin.py:188} INFO - Index(['hour', 'day_of_week', 'month', 'is_weekend', 'is_holiday', 'T',
       'heating_degree', 'cooling_degree', 'timestamp'],
      dtype='object')
[2025-04-28T19:17:16.224+0000] {logging_mixin.py:188} INFO - ‚ùå Error: column "timestamp" is of type timestamp with time zone but expression is of type bigint
LINE 3:     VALUES (1609459200000000000,10628.3759765625),(160946280...
                    ^
HINT:  You will need to rewrite or cast the expression.
[2025-04-28T19:17:16.231+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-28T19:17:16.242+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_forecast_dag, task_id=run_load_forecast, execution_date=20250428T191712, start_date=20250428T191714, end_date=20250428T191716
[2025-04-28T19:17:16.296+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T19:17:16.330+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
